# Generated by Django 2.2.5 on 2022-01-15 14:47

from django.db import migrations
import encryptedfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('encryptedfields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='test',
            field=encryptedfields.fields.FernetEncryptedTextField(blank=True, null=True),
        ),
    ]
