# Generated by Django 2.2.5 on 2022-01-15 16:20

from django.db import migrations
import encryptedfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('encryptedfields', '0002_testmodel_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='hidden',
            field=encryptedfields.fields.FernetEncryptedTextField(blank=True, null=True),
        ),
    ]
