name: build-and-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      DJANGO_SETTINGS_MODULE: tests.test_settings
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
        django-version: [3.1, 3.2, 4.0.1]
        exclude:
          - python-version: 3.7
            django-version: 4.0.1

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install Django==${{matrix.django-version}}
    - name: Run Tests
      run: |
        pytest
